using System;
using UnityEngine;

public struct Move {

    public string Name { get; }
    public PokemonType Type { get; }
    public MoveType MoveType { get; }
    public int BasePower { get; }
    public int PP { get; }
    public float Accuracy { get; }
    public bool AdditionalEffect { get; }
    public float AdditionalEffectProbability { get; }
    public AdditionalEffects AdditionalEffects { get; }

    public Move(Moves Index) {
        TextAsset MoveData = Resources.Load("MoveData") as TextAsset;
        string[] Data = MoveData.text.Split('\n')[(int)Index].Split('_');
        Name = Data[0];
        Type = new PokemonType(Data[1]);
        MoveType = (MoveType)Enum.Parse(typeof(MoveType), Data[2]);
        BasePower = int.Parse(Data[3]);
        PP = int.Parse(Data[4]);
        Accuracy = float.Parse(Data[5]);
        AdditionalEffect = Data[6] == "";
        AdditionalEffectProbability = AdditionalEffect ? float.Parse(Data[7]) : 0f;
        AdditionalEffects = AdditionalEffect ? GetAdditionalEffect(Data[8]) : AdditionalEffects.None;
    }

    public static AdditionalEffects GetAdditionalEffect(string Data) {
        if (Data.Contains("Inflict")) {
            if (Data.Contains("flinch")) { return AdditionalEffects.Flinch; }
            else 
            if (Data.Contains("burn")) { return AdditionalEffects.Burn; }
            else 
            if (Data.Contains("freeze")) { return AdditionalEffects.Freeze; }
            else 
            if (Data.Contains("paralysis")) { return AdditionalEffects.Paralysis; } 
            else 
            if (Data.Contains("confusion")) { return AdditionalEffects.Confusion; } 
            else 
            if (Data.Contains("sleep")) { return AdditionalEffects.Sleep; } 
            else 
            if (Data.Contains("poison")) { return AdditionalEffects.Poison; }
        }
        else if (Data.Contains("Lowers")) {
            if (Data.Contains("1 stage")) {
                if (Data.Contains("Attack")) { return AdditionalEffects.LowerStat1StageATTACK; }
                else
                if (Data.Contains("Defense")) { return AdditionalEffects.LowerStat1StageDEFENSE; } 
                else
                if (Data.Contains("Special Attack")) { return AdditionalEffects.LowerStat1StageSPECIAL_ATTACK; } else
                if (Data.Contains("Special Defense")) { return AdditionalEffects.LowerStat1StageSPECIAL_DEFENSE; } else
                if (Data.Contains("Speed")) { return AdditionalEffects.LowerStat1StageSPEED; } else
                if (Data.Contains("Evasion")) { return AdditionalEffects.LowerStat1StageEVASION; }
            } 
            else {
                if (Data.Contains("Attack")) { return AdditionalEffects.LowerStat2StageATTACK; } else
                if (Data.Contains("Defense")) { return AdditionalEffects.LowerStat2StageDEFENSE; } else
                if (Data.Contains("Special Attack")) { return AdditionalEffects.LowerStat2StageSPECIAL_ATTACK; } else
                if (Data.Contains("Special Defense")) { return AdditionalEffects.LowerStat2StageSPECIAL_DEFENSE; } else
                if (Data.Contains("Speed")) { return AdditionalEffects.LowerStat2StageSPEED; } else
                if (Data.Contains("Evasion")) { return AdditionalEffects.LowerStat2StageEVASION; }
            }
        } 
        else if (Data.Contains("Raises")) {
            if (Data.Contains("1 stage")) {
                if (Data.Contains("Attack")) { return AdditionalEffects.RaiseStat1StageATTACK; } else
                if (Data.Contains("Defense")) { return AdditionalEffects.RaiseStat1StageDEFENSE; } else
                if (Data.Contains("Special Attack")) { return AdditionalEffects.RaiseStat1StageSPECIAL_ATTACK; } else
                if (Data.Contains("Special Defense")) { return AdditionalEffects.RaiseStat1StageSPECIAL_DEFENSE; } else
                if (Data.Contains("Speed")) { return AdditionalEffects.RaiseStat1StageSPEED; } else
                if (Data.Contains("Evasion")) { return AdditionalEffects.RaiseStat1StageEVASION; }
            } else {
                if (Data.Contains("Attack")) { return AdditionalEffects.RaiseStat2StageATTACK; } else
                if (Data.Contains("Defense")) { return AdditionalEffects.RaiseStat2StageDEFENSE; } else
                if (Data.Contains("Special Attack")) { return AdditionalEffects.RaiseStat2StageSPECIAL_ATTACK; } else
                if (Data.Contains("Special Defense")) { return AdditionalEffects.RaiseStat2StageSPECIAL_DEFENSE; } else
                if (Data.Contains("Speed")) { return AdditionalEffects.RaiseStat2StageSPEED; } else
                if (Data.Contains("Evasion")) { return AdditionalEffects.RaiseStat2StageEVASION; }
            }
        } 
        else if (Data.Contains("Trap")) {
            return AdditionalEffects.Trap;
        }
        else if (Data.Contains(" PP ")) {
            return AdditionalEffects.ReducePP;
        }
        else if(Data.Contains("Prevents") && Data.Contains("sound-based")) {
            return AdditionalEffects.NoSound;
        }
        return AdditionalEffects.None;
    }

}
public enum Moves {
    Pound = 1,
    Karate_Chop = 2,
    Double_Slap = 3,
    Comet_Punch = 4,
    Mega_Punch = 5,
    Pay_Day = 6,
    Fire_Punch = 7,
    Ice_Punch = 8,
    Thunder_Punch = 9,
    Scratch = 10,
    Vise_Grip = 11,
    Guillotine = 12,
    Razor_Wind = 13,
    Swords_Dance = 14,
    Cut = 15,
    Gust = 16,
    Wing_Attack = 17,
    Whirlwind = 18,
    Fly = 19,
    Bind = 20,
    Slam = 21,
    Vine_Whip = 22,
    Stomp = 23,
    Double_Kick = 24,
    Mega_Kick = 25,
    Jump_Kick = 26,
    Rolling_Kick = 27,
    Sand_Attack = 28,
    Headbutt = 29,
    Horn_Attack = 30,
    Fury_Attack = 31,
    Horn_Drill = 32,
    Tackle = 33,
    Body_Slam = 34,
    Wrap = 35,
    Take_Down = 36,
    Thrash = 37,
    Double_Edge = 38,
    Tail_Whip = 39,
    Poison_Sting = 40,
    Twineedle = 41,
    Pin_Missile = 42,
    Leer = 43,
    Bite = 44,
    Growl = 45,
    Roar = 46,
    Sing = 47,
    Supersonic = 48,
    Sonic_Boom = 49,
    Disable = 50,
    Acid = 51,
    Ember = 52,
    Flamethrower = 53,
    Mist = 54,
    Water_Gun = 55,
    Hydro_Pump = 56,
    Surf = 57,
    Ice_Beam = 58,
    Blizzard = 59,
    Psybeam = 60,
    Bubble_Beam = 61,
    Aurora_Beam = 62,
    Hyper_Beam = 63,
    Peck = 64,
    Drill_Peck = 65,
    Submission = 66,
    Low_Kick = 67,
    Counter = 68,
    Seismic_Toss = 69,
    Strength = 70,
    Absorb = 71,
    Mega_Drain = 72,
    Leech_Seed = 73,
    Growth = 74,
    Razor_Leaf = 75,
    Solar_Beam = 76,
    Poison_Powder = 77,
    Stun_Spore = 78,
    Sleep_Powder = 79,
    Petal_Dance = 80,
    String_Shot = 81,
    Dragon_Rage = 82,
    Fire_Spin = 83,
    Thunder_Shock = 84,
    Thunderbolt = 85,
    Thunder_Wave = 86,
    Thunder = 87,
    Rock_Throw = 88,
    Earthquake = 89,
    Fissure = 90,
    Dig = 91,
    Toxic = 92,
    Confusion = 93,
    Psychic = 94,
    Hypnosis = 95,
    Meditate = 96,
    Agility = 97,
    Quick_Attack = 98,
    Rage = 99,
    Teleport = 100,
    Night_Shade = 101,
    Mimic = 102,
    Screech = 103,
    Double_Team = 104,
    Recover = 105,
    Harden = 106,
    Minimize = 107,
    Smokescreen = 108,
    Confuse_Ray = 109,
    Withdraw = 110,
    Defense_Curl = 111,
    Barrier = 112,
    Light_Screen = 113,
    Haze = 114,
    Reflect = 115,
    Focus_Energy = 116,
    Bide = 117,
    Metronome = 118,
    Mirror_Move = 119,
    Self_Destruct = 120,
    Egg_Bomb = 121,
    Lick = 122,
    Smog = 123,
    Sludge = 124,
    Bone_Club = 125,
    Fire_Blast = 126,
    Waterfall = 127,
    Clamp = 128,
    Swift = 129,
    Skull_Bash = 130,
    Spike_Cannon = 131,
    Constrict = 132,
    Amnesia = 133,
    Kinesis = 134,
    Soft_Boiled = 135,
    High_Jump_Kick = 136,
    Glare = 137,
    Dream_Eater = 138,
    Poison_Gas = 139,
    Barrage = 140,
    Leech_Life = 141,
    Lovely_Kiss = 142,
    Sky_Attack = 143,
    Transform = 144,
    Bubble = 145,
    Dizzy_Punch = 146,
    Spore = 147,
    Flash = 148,
    Psywave = 149,
    Splash = 150,
    Acid_Armor = 151,
    Crabhammer = 152,
    Explosion = 153,
    Fury_Swipes = 154,
    Bonemerang = 155,
    Rest = 156,
    Rock_Slide = 157,
    Hyper_Fang = 158,
    Sharpen = 159,
    Conversion = 160,
    Tri_Attack = 161,
    Super_Fang = 162,
    Slash = 163,
    Substitute = 164,
    Struggle = 165,
    Sketch = 166,
    Triple_Kick = 167,
    Thief = 168,
    Spider_Web = 169,
    Mind_Reader = 170,
    Nightmare = 171,
    Flame_Wheel = 172,
    Snore = 173,
    Curse = 174,
    Flail = 175,
    Conversion_2 = 176,
    Aeroblast = 177,
    Cotton_Spore = 178,
    Reversal = 179,
    Spite = 180,
    Powder_Snow = 181,
    Protect = 182,
    Mach_Punch = 183,
    Scary_Face = 184,
    Feint_Attack = 185,
    Sweet_Kiss = 186,
    Belly_Drum = 187,
    Sludge_Bomb = 188,
    Mud_Slap = 189,
    Octazooka = 190,
    Spikes = 191,
    Zap_Cannon = 192,
    Foresight = 193,
    Destiny_Bond = 194,
    Perish_Song = 195,
    Icy_Wind = 196,
    Detect = 197,
    Bone_Rush = 198,
    Lock_On = 199,
    Outrage = 200,
    Sandstorm = 201,
    Giga_Drain = 202,
    Endure = 203,
    Charm = 204,
    Rollout = 205,
    False_Swipe = 206,
    Swagger = 207,
    Milk_Drink = 208,
    Spark = 209,
    Fury_Cutter = 210,
    Steel_Wing = 211,
    Mean_Look = 212,
    Attract = 213,
    Sleep_Talk = 214,
    Heal_Bell = 215,
    Return = 216,
    Present = 217,
    Frustration = 218,
    Safeguard = 219,
    Pain_Split = 220,
    Sacred_Fire = 221,
    Magnitude = 222,
    Dynamic_Punch = 223,
    Megahorn = 224,
    Dragon_Breath = 225,
    Baton_Pass = 226,
    Encore = 227,
    Pursuit = 228,
    Rapid_Spin = 229,
    Sweet_Scent = 230,
    Iron_Tail = 231,
    Metal_Claw = 232,
    Vital_Throw = 233,
    Morning_Sun = 234,
    Synthesis = 235,
    Moonlight = 236,
    Hidden_Power = 237,
    Cross_Chop = 238,
    Twister = 239,
    Rain_Dance = 240,
    Sunny_Day = 241,
    Crunch = 242,
    Mirror_Coat = 243,
    Psych_Up = 244,
    Extreme_Speed = 245,
    Ancient_Power = 246,
    Shadow_Ball = 247,
    Future_Sight = 248,
    Rock_Smash = 249,
    Whirlpool = 250,
    Beat_Up = 251,
    Fake_Out = 252,
    Uproar = 253,
    Stockpile = 254,
    Spit_Up = 255,
    Swallow = 256,
    Heat_Wave = 257,
    Hail = 258,
    Torment = 259,
    Flatter = 260,
    Will_O_Wisp = 261,
    Memento = 262,
    Facade = 263,
    Focus_Punch = 264,
    Smelling_Salts = 265,
    Follow_Me = 266,
    Nature_Power = 267,
    Charge = 268,
    Taunt = 269,
    Helping_Hand = 270,
    Trick = 271,
    Role_Play = 272,
    Wish = 273,
    Assist = 274,
    Ingrain = 275,
    Superpower = 276,
    Magic_Coat = 277,
    Recycle = 278,
    Revenge = 279,
    Brick_Break = 280,
    Yawn = 281,
    Knock_Off = 282,
    Endeavor = 283,
    Eruption = 284,
    Skill_Swap = 285,
    Imprison = 286,
    Refresh = 287,
    Grudge = 288,
    Snatch = 289,
    Secret_Power = 290,
    Dive = 291,
    Arm_Thrust = 292,
    Camouflage = 293,
    Tail_Glow = 294,
    Luster_Purge = 295,
    Mist_Ball = 296,
    Feather_Dance = 297,
    Teeter_Dance = 298,
    Blaze_Kick = 299,
    Mud_Sport = 300,
    Ice_Ball = 301,
    Needle_Arm = 302,
    Slack_Off = 303,
    Hyper_Voice = 304,
    Poison_Fang = 305,
    Crush_Claw = 306,
    Blast_Burn = 307,
    Hydro_Cannon = 308,
    Meteor_Mash = 309,
    Astonish = 310,
    Weather_Ball = 311,
    Aromatherapy = 312,
    Fake_Tears = 313,
    Air_Cutter = 314,
    Overheat = 315,
    Odor_Sleuth = 316,
    Rock_Tomb = 317,
    Silver_Wind = 318,
    Metal_Sound = 319,
    Grass_Whistle = 320,
    Tickle = 321,
    Cosmic_Power = 322,
    Water_Spout = 323,
    Signal_Beam = 324,
    Shadow_Punch = 325,
    Extrasensory = 326,
    Sky_Uppercut = 327,
    Sand_Tomb = 328,
    Sheer_Cold = 329,
    Muddy_Water = 330,
    Bullet_Seed = 331,
    Aerial_Ace = 332,
    Icicle_Spear = 333,
    Iron_Defense = 334,
    Block = 335,
    Howl = 336,
    Dragon_Claw = 337,
    Frenzy_Plant = 338,
    Bulk_Up = 339,
    Bounce = 340,
    Mud_Shot = 341,
    Poison_Tail = 342,
    Covet = 343,
    Volt_Tackle = 344,
    Magical_Leaf = 345,
    Water_Sport = 346,
    Calm_Mind = 347,
    Leaf_Blade = 348,
    Dragon_Dance = 349,
    Rock_Blast = 350,
    Shock_Wave = 351,
    Water_Pulse = 352,
    Doom_Desire = 353,
    Psycho_Boost = 354,
    Roost = 355,
    Gravity = 356,
    Miracle_Eye = 357,
    Wake_Up_Slap = 358,
    Hammer_Arm = 359,
    Gyro_Ball = 360,
    Healing_Wish = 361,
    Brine = 362,
    Natural_Gift = 363,
    Feint = 364,
    Pluck = 365,
    Tailwind = 366,
    Acupressure = 367,
    Metal_Burst = 368,
    U_turn = 369,
    Close_Combat = 370,
    Payback = 371,
    Assurance = 372,
    Embargo = 373,
    Fling = 374,
    Psycho_Shift = 375,
    Trump_Card = 376,
    Heal_Block = 377,
    Wring_Out = 378,
    Power_Trick = 379,
    Gastro_Acid = 380,
    Lucky_Chant = 381,
    Me_First = 382,
    Copycat = 383,
    Power_Swap = 384,
    Guard_Swap = 385,
    Punishment = 386,
    Last_Resort = 387,
    Worry_Seed = 388,
    Sucker_Punch = 389,
    Toxic_Spikes = 390,
    Heart_Swap = 391,
    Aqua_Ring = 392,
    Magnet_Rise = 393,
    Flare_Blitz = 394,
    Force_Palm = 395,
    Aura_Sphere = 396,
    Rock_Polish = 397,
    Poison_Jab = 398,
    Dark_Pulse = 399,
    Night_Slash = 400,
    Aqua_Tail = 401,
    Seed_Bomb = 402,
    Air_Slash = 403,
    X_Scissor = 404,
    Bug_Buzz = 405,
    Dragon_Pulse = 406,
    Dragon_Rush = 407,
    Power_Gem = 408,
    Drain_Punch = 409,
    Vacuum_Wave = 410,
    Focus_Blast = 411,
    Energy_Ball = 412,
    Brave_Bird = 413,
    Earth_Power = 414,
    Switcheroo = 415,
    Giga_Impact = 416,
    Nasty_Plot = 417,
    Bullet_Punch = 418,
    Avalanche = 419,
    Ice_Shard = 420,
    Shadow_Claw = 421,
    Thunder_Fang = 422,
    Ice_Fang = 423,
    Fire_Fang = 424,
    Shadow_Sneak = 425,
    Mud_Bomb = 426,
    Psycho_Cut = 427,
    Zen_Headbutt = 428,
    Mirror_Shot = 429,
    Flash_Cannon = 430,
    Rock_Climb = 431,
    Defog = 432,
    Trick_Room = 433,
    Draco_Meteor = 434,
    Discharge = 435,
    Lava_Plume = 436,
    Leaf_Storm = 437,
    Power_Whip = 438,
    Rock_Wrecker = 439,
    Cross_Poison = 440,
    Gunk_Shot = 441,
    Iron_Head = 442,
    Magnet_Bomb = 443,
    Stone_Edge = 444,
    Captivate = 445,
    Stealth_Rock = 446,
    Grass_Knot = 447,
    Chatter = 448,
    Judgment = 449,
    Bug_Bite = 450,
    Charge_Beam = 451,
    Wood_Hammer = 452,
    Aqua_Jet = 453,
    Attack_Order = 454,
    Defend_Order = 455,
    Heal_Order = 456,
    Head_Smash = 457,
    Double_Hit = 458,
    Roar_of_Time = 459,
    Spacial_Rend = 460,
    Lunar_Dance = 461,
    Crush_Grip = 462,
    Magma_Storm = 463,
    Dark_Void = 464,
    Seed_Flare = 465,
    Ominous_Wind = 466,
    Shadow_Force = 467,
    Hone_Claws = 468,
    Wide_Guard = 469,
    Guard_Split = 470,
    Power_Split = 471,
    Wonder_Room = 472,
    Psyshock = 473,
    Venoshock = 474,
    Autotomize = 475,
    Rage_Powder = 476,
    Telekinesis = 477,
    Magic_Room = 478,
    Smack_Down = 479,
    Storm_Throw = 480,
    Flame_Burst = 481,
    Sludge_Wave = 482,
    Quiver_Dance = 483,
    Heavy_Slam = 484,
    Synchronoise = 485,
    Electro_Ball = 486,
    Soak = 487,
    Flame_Charge = 488,
    Coil = 489,
    Low_Sweep = 490,
    Acid_Spray = 491,
    Foul_Play = 492,
    Simple_Beam = 493,
    Entrainment = 494,
    After_You = 495,
    Round = 496,
    Echoed_Voice = 497,
    Chip_Away = 498,
    Clear_Smog = 499,
    Stored_Power = 500,
    Quick_Guard = 501,
    Ally_Switch = 502,
    Scald = 503,
    Shell_Smash = 504,
    Heal_Pulse = 505,
    Hex = 506,
    Sky_Drop = 507,
    Shift_Gear = 508,
    Circle_Throw = 509,
    Incinerate = 510,
    Quash = 511,
    Acrobatics = 512,
    Reflect_Type = 513,
    Retaliate = 514,
    Final_Gambit = 515,
    Bestow = 516,
    Inferno = 517,
    Water_Pledge = 518,
    Fire_Pledge = 519,
    Grass_Pledge = 520,
    Volt_Switch = 521,
    Struggle_Bug = 522,
    Bulldoze = 523,
    Frost_Breath = 524,
    Dragon_Tail = 525,
    Work_Up = 526,
    Electroweb = 527,
    Wild_Charge = 528,
    Drill_Run = 529,
    Dual_Chop = 530,
    Heart_Stamp = 531,
    Horn_Leech = 532,
    Sacred_Sword = 533,
    Razor_Shell = 534,
    Heat_Crash = 535,
    Leaf_Tornado = 536,
    Steamroller = 537,
    Cotton_Guard = 538,
    Night_Daze = 539,
    Psystrike = 540,
    Tail_Slap = 541,
    Hurricane = 542,
    Head_Charge = 543,
    Gear_Grind = 544,
    Searing_Shot = 545,
    Techno_Blast = 546,
    Relic_Song = 547,
    Secret_Sword = 548,
    Glaciate = 549,
    Bolt_Strike = 550,
    Blue_Flare = 551,
    Fiery_Dance = 552,
    Freeze_Shock = 553,
    Ice_Burn = 554,
    Snarl = 555,
    Icicle_Crash = 556,
    V_create = 557,
    Fusion_Flare = 558,
    Fusion_Bolt = 559,
    Flying_Press = 560,
    Mat_Block = 561,
    Belch = 562,
    Rototiller = 563,
    Sticky_Web = 564,
    Fell_Stinger = 565,
    Phantom_Force = 566,
    Trick_or_Treat = 567,
    Noble_Roar = 568,
    Ion_Deluge = 569,
    Parabolic_Charge = 570,
    Forests_Curse = 571,
    Petal_Blizzard = 572,
    Freeze_Dry = 573,
    Disarming_Voice = 574,
    Parting_Shot = 575,
    Topsy_Turvy = 576,
    Draining_Kiss = 577,
    Crafty_Shield = 578,
    Flower_Shield = 579,
    Grassy_Terrain = 580,
    Misty_Terrain = 581,
    Electrify = 582,
    Play_Rough = 583,
    Fairy_Wind = 584,
    Moonblast = 585,
    Boomburst = 586,
    Fairy_Lock = 587,
    Kings_Shield = 588,
    Play_Nice = 589,
    Confide = 590,
    Diamond_Storm = 591,
    Steam_Eruption = 592,
    Hyperspace_Hole = 593,
    Water_Shuriken = 594,
    Mystical_Fire = 595,
    Spiky_Shield = 596,
    Aromatic_Mist = 597,
    Eerie_Impulse = 598,
    Venom_Drench = 599,
    Powder = 600,
    Geomancy = 601,
    Magnetic_Flux = 602,
    Happy_Hour = 603,
    Electric_Terrain = 604,
    Dazzling_Gleam = 605,
    Celebrate = 606,
    Hold_Hands = 607,
    Baby_Doll_Eyes = 608,
    Nuzzle = 609,
    Hold_Back = 610,
    Infestation = 611,
    Power_Up_Punch = 612,
    Oblivion_Wing = 613,
    Thousand_Arrows = 614,
    Thousand_Waves = 615,
    Lands_Wrath = 616,
    Light_of_Ruin = 617,
    Origin_Pulse = 618,
    Precipice_Blades = 619,
    Dragon_Ascent = 620,
    Hyperspace_Fury = 621,
    Shore_Up = 622,
    First_Impression = 623,
    Baneful_Bunker = 624,
    Spirit_Shackle = 625,
    Darkest_Lariat = 626,
    Sparkling_Aria = 627,
    Ice_Hammer = 628,
    Floral_Healing = 629,
    High_Horsepower = 630,
    Strength_Sap = 631,
    Solar_Blade = 632,
    Leafage = 633,
    Spotlight = 634,
    Toxic_Thread = 635,
    Laser_Focus = 636,
    Gear_Up = 637,
    Throat_Chop = 638,
    Pollen_Puff = 639,
    Anchor_Shot = 640,
    Psychic_Terrain = 641,
    Lunge = 642,
    Fire_Lash = 643,
    Power_Trip = 644,
    Burn_Up = 645,
    Speed_Swap = 646,
    Smart_Strike = 647,
    Purify = 648,
    Revelation_Dance = 649,
    Core_Enforcer = 650,
    Trop_Kick = 651,
    Instruct = 652,
    Beak_Blast = 653,
    Clanging_Scales = 654,
    Dragon_Hammer = 655,
    Brutal_Swing = 656,
    Aurora_Veil = 657,
    Shell_Trap = 658,
    Fleur_Cannon = 659,
    Psychic_Fangs = 660,
    Stomping_Tantrum = 661,
    Shadow_Bone = 662,
    Accelerock = 663,
    Liquidation = 664,
    Prismatic_Laser = 665,
    Spectral_Thief = 666,
    Sunsteel_Strike = 667,
    Moongeist_Beam = 668,
    Tearful_Look = 669,
    Zing_Zap = 670,
    Natures_Madness = 671,
    Multi_Attack = 672,
    Mind_Blown = 673,
    Plasma_Fists = 674,
    Photon_Geyser = 675,
    Lets_Snuggle_Forever = 676,
    Zippy_Zap = 677,
    Splishy_Splash = 678,
    Floaty_Fall = 679,
    Pika_Papow = 680,
    Bouncy_Bubble = 681,
    Buzzy_Buzz = 682,
    Sizzly_Slide = 683,
    Glitzy_Glow = 684,
    Baddy_Bad = 685,
    Sappy_Seed = 686,
    Freezy_Frost = 687,
    Sparkly_Swirl = 688,
    Veevee_Volley = 689,
    Double_Iron_Bash = 690,
    Dynamax_Cannon = 691,
    Snipe_Shot = 692,
    Jaw_Lock = 693,
    Stuff_Cheeks = 694,
    No_Retreat = 695,
    Tar_Shot = 696,
    Magic_Powder = 697,
    Dragon_Darts = 698,
    Teatime = 699,
    Octolock = 700,
    Bolt_Beak = 701,
    Fishious_Rend = 702,
    Court_Change = 703,
    Clangorous_Soul = 704,
    Body_Press = 705,
    Decorate = 706,
    Drum_Beating = 707,
    Snap_Trap = 708,
    Pyro_Ball = 709,
    Behemoth_Blade = 710,
    Behemoth_Bash = 711,
    Aura_Wheel = 712,
    Breaking_Swipe = 713,
    Branch_Poke = 714,
    Overdrive = 715,
    Apple_Acid = 716,
    Grav_Apple = 717,
    Spirit_Break = 718,
    Strange_Steam = 719,
    Life_Dew = 720,
    Obstruct = 721,
    False_Surrender = 722,
    Meteor_Assault = 723,
    Eternabeam = 724,
    Steel_Beam = 725,
    Expanding_Force = 726,
    Steel_Roller = 727,
    Scale_Shot = 728,
    Meteor_Beam = 729,
    Shell_Side_Arm = 730,
    Misty_Explosion = 731,
    Grassy_Glide = 732,
    Rising_Voltage = 733,
    Terrain_Pulse = 734,
    Skitter_Smack = 735,
    Burning_Jealousy = 736,
    Lash_Out = 737,
    Poltergeist = 738,
    Corrosive_Gas = 739,
    Coaching = 740,
    Flip_Turn = 741,
    Triple_Axel = 742,
    Dual_Wingbeat = 743,
    Scorching_Sands = 744,
    Jungle_Healing = 745,
    Wicked_Blow = 746,
    Surging_Strikes = 747,
    Thunder_Cage = 748,
    Dragon_Energy = 749,
    Freezing_Glare = 750,
    Fiery_Wrath = 751,
    Thunderous_Kick = 752,
    Glacial_Lance = 753,
    Astral_Barrage = 754,
    Eerie_Spell = 755,
    Dire_Claw = 756,
    Psyshield_Bash = 757,
    Power_Shift = 758,
    Stone_Axe = 759,
    Springtide_Storm = 760,
    Mystical_Power = 761,
    Raging_Fury = 762,
    Wave_Crash = 763,
    Chloroblast = 764,
    Mountain_Gale = 765,
    Victory_Dance = 766,
    Headlong_Rush = 767,
    Barb_Barrage = 768,
    Esper_Wing = 769,
    Bitter_Malice = 770,
    Shelter = 771,
    Triple_Arrows = 772,
    Infernal_Parade = 773,
    Ceaseless_Edge = 774,
    Bleakwind_Storm = 775,
    Wildbolt_Storm = 776,
    Sandsear_Storm = 777,
    Lunar_Blessing = 778,
    Take_Heart = 779,
    Forme_Change = 780,
}
public enum AdditionalEffects {
    None,
    Trap,
    ReducePP,
    RaiseStat1StageHP,
    RaiseStat1StageATTACK,
    RaiseStat1StageDEFENSE,
    RaiseStat1StageSPECIAL_ATTACK,
    RaiseStat1StageSPECIAL_DEFENSE,
    RaiseStat1StageSPEED,
    RaiseStat1StageEVASION,
    RaiseStat2StageHP,
    RaiseStat2StageATTACK,
    RaiseStat2StageDEFENSE,
    RaiseStat2StageSPECIAL_ATTACK,
    RaiseStat2StageSPECIAL_DEFENSE,
    RaiseStat2StageSPEED,
    RaiseStat2StageEVASION,
    RaiseAllStat1,
    RaiseAllStat2,
    LowerStat1StageHP,
    LowerStat1StageATTACK,
    LowerStat1StageDEFENSE,
    LowerStat1StageSPECIAL_ATTACK,
    LowerStat1StageSPECIAL_DEFENSE,
    LowerStat1StageSPEED,
    LowerStat1StageEVASION,
    LowerStat2StageHP,
    LowerStat2StageATTACK,
    LowerStat2StageDEFENSE,
    LowerStat2StageSPECIAL_ATTACK,
    LowerStat2StageSPECIAL_DEFENSE,
    LowerStat2StageSPEED,
    LowerStat2StageEVASION,
    NoSound,
    NonVolitileStatusCondition,
    VolitileStatusCondition,
    Flinch,
    Cure,
    ChangeForme,
    BattleStatus,
    AquaRing,
    Bracing,
    Charging,
    Attention,
    DefensiveCurl,
    Rooting,
    MagicCoat,
    Levitating,
    Mimic,
    Minimize,
    Protect,
    Recharging,
    Invulnerable,
    Subsitute,
    TakingAim,
    Thrashing,
    Bound,
    Confusion,
    Curse,
    Encore,
    HealBlock,
    Identified,
    Infatuation,
    LeechSeed,
    Nightmare,
    PerishSong,
    Taunt,
    Telekinesis,
    Torment,
    TypeChange,
    Sleep,
    Poison,
    Paralysis,
    Freeze,
    Burn,
}
public enum MoveType {
    Special,
    Physical,
    Status
}